### ISSUE TITLE
Screenshots are not being uploaded

### ISSUE THREAD

**Issue by odisseus** [VirtusLab/intellij-pants-plugin-tests#80]
It looks like they aren't even generated.

Last commit for which screenshots were generated: c7d3f9355666e77e45d73d8bce6fe15db95cd2fe

First affected commit: e3e29becb97088a9aa7ff8b18d298587916e751d

First affected PR: https://github.com/VirtusLab/intellij-pants-plugin-tests/pull/72

**Comment by lukaszwawrzyk** [comment]
I don't see anything suspicious in code except for ide-probe version bump. It might be, that the version contained the configurable paths feature and screenshots path is now different. We need to investigate this.
